### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#133]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

Add native support for SOCKS proxies and HTTP proxies via the CONNECT method.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/136

**Comment by NicolasLM** [comment]
I don't think that this is a very commonly requested feature and adding support for socks or HTTP CONNECT would likely imply adding additional dependencies to IMAPClient.

Instead of implementing the proxies ourselves, we can make it easy for users to use the proxy mechanism of their choice by hooking into IMAPClient.

I have successfully done something similar by subclassing `smtplib.SMTP` and overriding its `_get_socket()` method. This could work for IMAPClient as well.

**Comment by mjs** [comment]
Unlikely to do this.

**Comment by ngugcx** [comment]
> I don't think that this is a very commonly requested feature and adding support for socks or HTTP CONNECT would likely imply adding additional dependencies to IMAPClient.
> 
> Instead of implementing the proxies ourselves, we can make it easy for users to use the proxy mechanism of their choice by hooking into IMAPClient.
> 
> I have successfully done something similar by subclassing `smtplib.SMTP` and overriding its `_get_socket()` method. This could work for IMAPClient as well.

Is there an example of how to do this with IMAPClient? Thanks.
