### ISSUE TITLE
ptpython support for interact shell

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#272]
https://github.com/jonathanslenders/ptpython

Embedding looks very easy:
https://github.com/jonathanslenders/ptpython/blob/master/examples/python-embed.py

**Comment by NicolasLM** [comment]
I don't really get the point, IMHO alternative shell users are tech savvy enough to prefer the three lines needed to get a logged in IMAPClient instance rather than relying on every library they use to have shortcuts to their shells.

Am I missing something?

**Comment by mlorant** [comment]
I like when libraries/frameworks are opening shell with iPython because I'm used to it although I also don't mind having the regular Python shell either
On the other hand, supporting another shell alternative is just five lines of code, in a non-critical part (performance does not really matter there, we could try dozens of imports), so if someone is using it, why not...

I have several test accounts (for debugging our own code against real use cases manually) and I don't recall the host addresses and passwords of all of them. So, I'm am using the `interact` shell launcher with config files to bootstrap a session with the client initialized. I get the idea why it can be useful, so if someone is so interesting in ptpython, it can be valid :)

**Comment by mjs** [comment]
As per @mlorant, I use `python -m imapclient.interact` all the time and have it drop me into an IPython shell is so nice. `ptpython` is arguably even nicer.

IPython and ptpython don't support `-m <some-module>` easily so having the IMAPClient interact shell automatically embed them if they're installed is nice.

As @mlorant said, the code required to do this is minimal.
