### ISSUE TITLE
Socket errors at scale

### ISSUE THREAD

**Issue by dsanghan** [mjs/imapclient#323]
Running around 5000+ concurrent IMAPClient instances (each instance is on its own thread) does not work - netdata reports a lot of socket issues. 

<img width="741" alt="screen shot 2017-12-14 at 6 52 21 pm" src="https://user-images.githubusercontent.com/6698354/33994394-5828bfe0-e100-11e7-8115-fdd129847239.png">

I read `select.select` cannot use fd's above 1024 as reported in: https://github.com/mjs/imapclient/issues/280  - which is why I replaced `select.select` with `selectors2.DefaultSelector()`  https://github.com/dsanghan/imapclient/commit/7e518df6f4826d8e5e1f781a238ec7f8b93f189f and https://github.com/dsanghan/imapclient/commit/7f37b3d7956c4c46138010fca0e4fabe07722cb6. I'm probably doing something wrong with how `DefaultSelector()` is being used.

The server basically becomes unresponsive with consistently high CPU usage - any ideas how I'd go about fixing this? At low concurrency ~20 accounts, everything works properly.

Also, 5000+ concurrent imaplib instances work fine - only utilize about 20% cpu, so context switching, fd limits, etc are not the limitation here.

**Comment by NicolasLM** [comment]
I use IMAPClient to listen for IDLE events on thousand of mailboxes.

I don't think that one thread per IDLE connection is a good approach mainly because of context switches and memory pressure.

So I went ahead and developed a small algorithm on top of IMAPClient to await these connections asynchronously in a single thread. It is basically:
- a thread pool that opens IMAPClient instances, starts IDLE and switches sockets to non-blocking
- a single thread that uses `DefaultSelector` to await events on these sockets and puts notifications in a `queue.Queue`
- another thread that periodically renews IDLE connections (every 10 minutes is the sweet spot)

Keep in mind that maintaining TCP connections opened for a long time is not something the Internet is very used to. Be ready to handle all kind of errors related to sockets (even sockets dropped without sending an RST). I eventually had to add a blacklist that stops trying to IDLE some servers showing bad behavior.

**Comment by NicolasLM** [comment]
As for why it works for you with `imaplib` and not with `IMAPClient`, my guess is that OSes are not designed to have 5000 calls to `epoll`/`kqueue` each awaiting a single fd.

**Comment by dsanghan** [comment]
Hmm, interesting. That does sound like a better way to go about it. I'll try it out. 

As for using defaultSelector, I'm assuming a quick fix would be to have all the sockets on one selector instead of using individual selectors.

**Comment by NicolasLM** [comment]
As maintaining a lot of IDLE connections is more tricky than it looks, I will check if I can open source the code I wrote. It would probably be useful to others and would remove some maintenance burden on me.

**Comment by dsanghan** [comment]
Ok cool. That would be super useful. Does your code revert to polling for accounts that either do not have IDLE support or have IDLE but it works poorly (socket drops, etc)?

**Comment by dsanghan** [comment]
@NicolasLM: Got everything working. Thread pool + defaultSelector + auto IDLE refreshes + polling for non IDLE providers. Thanks for the help (and the code)! 

Performance is also good.
