### ISSUE TITLE
Idle Expunge position instead of uid

### ISSUE THREAD

**Issue by Bastilla123** [mjs/imapclient#443]
Hello,

my code is:

imap_client = IMAPClient(host, use_uid=True, ssl=True)
    imap_client.login(user, imappassword)
    imap_client.select_folder("INBOX")
    idle = imap_client.idle()

    while True:
        msg = imap_client.idle_check(timeout=60)
        if (msg!=""):
           print(msg)

imap server is a dovecot server. Now when i delete with Thunderbird a E-Mail i get as response the position of e-mail and not uid. Is set use_uid_True but this doesn't work. What's wrong here?

Regards

**Comment by mjs** [comment]
IDLE responses sent by different IMAP servers vary quite a bit. Also, the number in the responses typically indicate an amount of messages, not message sequence numbers or UIDs.

For example, an IDLE response of:

```
* 3 EXPUNGE
``` 

Means that "3 messages were expunged", not "message number 3 was expunged.

My advice would be to use IDLE responses only to know that "something" has happened rather than trying to interpret too much from them. Additional searches should be used to determine what actually happened.

There's not much more that IMAPClient do to help here.
